# Generated by Django 5.0.1 on 2025-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0008_event_team_size_teammate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
